name: "Dakani Labs"
description: "Jekyll-powered webpage for Dakani"
url: "dakanilabs.com"

auto: false
server: false
server_port: 4000
source: .
destination: ./_site
plugins: ./_plugins
exclude: [.git/,update.sh]

lsi: true
paginate: 15

markdown: rdiscount
permalink: pretty
pygments: true