name: "Dakani Labs"
description: "Jekyll-powered webpage for Dakani"
url: "dakanilabs.com"

auto: false
server: false
server_port: 4000
source: .
destination: ./_site
plugins: ./_plugins
exclude: [.git/,update.sh]

lsi: true
paginate: 15

markdown: rdiscount
permalink: pretty
pygments: true

author_ids: [vincent]
authors:
    vincent:
        display_name: Vincent Deloso
        gravatar: 5ed6fc41ebf7d88590a4c07eae074e97
        email: mitsugaru@gmail.com
        web: http://www.dakanilabs.com
        twitter: tokume
        github: mitsugaru
        job_title: Software Engineer
        bio: Nothing here for now.